credentials:
  usernames:
    valiant:
      email: vezabuku09@gmail.com
      name: Adiru Valiant Ezabuku
      password: '123456'  # This should be a hashed password
cookie:
  expiry_days: 0
  key: cookie_signature_key
  name: cookie_name
preauthorized:
  usernames:
  - valiant
